info:
  app: Sample APP

datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

jpa:
  default:
    packages-to-scan: org.quickperf.micronaut.micronauttest.jpa.entity
    properties:
      hibernate:
        hbm2ddl:
          auto: drop-and-create
        show_sql: true